no_llseek no longer available >= 6.12, name changed to a more correct noop_llseek name
error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
   90 |  .llseek = no_llseek,
      |            ^~~~~~~~~
      |            noop_llseek